name: chirpy 
channels:
  - conda-forge
  - defaults
dependencies:
  - fortranformat=0.2.*
  - ipython=7.*
  - jupyter=1.*
  - jupyter_core=4.*
  - matplotlib=3.*
  - mdanalysis=1.* 
  - numpy=1.*
  - packmol=20.*
  - periodictable=1.*
  - pip=20.*
  - pycifrw=4.*
  - python=3.8.*
  - scipy=1.*
